---
exp_dir: experiment_files/
data_path: data/
seed: 123

model:
  name: AGE
  ablation: True
  hidden_size: 256
  encoder:
    num_layers: 6
    num_attn_heads: 8
    dim_feedforward: 1024
    dropout: 0.0
  decoder:
    num_layers: 6
    num_attn_heads: 2
    dim_feedforward: 1024
    dropout: 0.0

experiment:
  device: 0
  train:
    batch_size: 128
    shuffle_data: True
    epochs: 20000
    optimizer: Adam
    lr: 0.001
    lr_decay: 0.3  # For milestone based decay
    weight_decay: 0.0005  # Regularisation-type term in Adam
    snapshot_epochs: 100  # How often to save the model (not including validation)
    display_iters: 1  # How often to print output
    accum_grad: 1
    clip_grad: 5
    use_writer: False  # Flag for tensorboard.
    n_workers: 8

  validation:
    es_buffer: 50  # Burn in period for early stopping
    val_epochs: 1  # Interval between validation epochs
    es_patience: 20  # How many times to validate with no improvement before stopping
    batch_size: 32
    patience: 15
    decay_factor: 0.1
    min_lr: 1e-6
    cooldown: 10
